language: node_js
node_js:
    - 0.8
    - 0.6

before_install:
  - wget http://libav.org/releases/libav-9.1.tar.gz
  - tar -xvf libav-9.1.tar.gz
  - cd libav-9.1
  - ./configure
  - make
  - sudo make install
